# Generated by Django 5.2.5 on 2025-10-04 12:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fuel_type', models.CharField(choices=[('petrol', 'Benzin'), ('diesel', 'Dizel'), ('electric', 'Elektro'), ('hybrid', 'Gibrid')], max_length=20)),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.color')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('phone_number', models.CharField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
